name: Feature request
description: Proposer une fonctionnalité documentée
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Besoin
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
    validations:
      required: true
